### ISSUE TITLE
Encode array entries with extra []

### ISSUE THREAD

**Issue by bobojo** [ydeshayes/to-querystring#1]
Unless I'm mistaken, in order for a query string to be interpreted as an array, it needs an extra pair of square brackets, i.e. `array: [ 'item1', 'item2', 'item3' ]` becomes `array[]=item1&array[]=item2&array[]=item3`. Currently, that array would be converted to `array=item1&array=item2&array=item3` instead. Is there a reason for this, or is this something that can be fixed?

**Comment by ydeshayes** [comment]
Hello,

There is a lot of ways to describe/read an array in a query string, it depend on the language and the framework/libs you are using.

I added a new option param in the 1.1.0 version. You can find how to use it https://github.com/ydeshayes/to-querystring/blob/master/tests/objectToQueryString.spec.js#L16

I'll update the README soon.

**Comment by bobojo** [comment]
Yeah, I realized after I left that comment that this syntax isn't universal. Thanks for providing an appropriate solution!
